[package]
authors = ["steveklabnik <steve@steveklabnik.com>"]
name = "dir-diff"
version = "0.1.0"
description = "Do two directories have different contents?"
license = "MIT/Apache-2.0"
repository = "https://github.com/steveklabnik/dir-diff"
documentation = "https://docs.rs/dir-diff"
readme = "README.md"
tags = ["directory", "diff", "fs"]

[dependencies]
diff = "0.1.10"
walkdir = "1.0.7"
