[package]
authors = ["steveklabnik <steve@steveklabnik.com>"]
name = "dir-diff"
version = "0.1.0"
description = "Do two directories have different contents?"
license = "MIT/Apache-2.0"
repository = "https://github.com/steveklabnik/dir-diff"

[dependencies]
diff = "0.1.10"
walkdir = "1.0.7"
